<?xml version="1.0"?>
<!-- Dual Motor Test URDF using FR Arm structure for 2 MyActuator RMD motors -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="dual_motor_test">
    
    <!-- Include inertial macros from robot_description -->
    <xacro:include filename="$(find robot_description)/urdf/arm_only/inertial_macros.xacro"/>

    <!-- Arguments -->
    <xacro:arg name="can_interface" default="can0"/>
    <xacro:arg name="motor1_id" default="1"/>
    <xacro:arg name="motor2_id" default="2"/>

    <!-- Properties from robot_description -->
    <xacro:property name="meshes_file_direction" value="package://robot_description/meshes"/>
    <xacro:property name="actuator_height" value="0.061"/>
    <xacro:property name="actuator_diameter" value="0.065"/>
    <xacro:property name="actuator_radius" value="${actuator_diameter / 2}"/>
    <xacro:property name="actuator_mass" value="0.350"/>
    <xacro:property name="actuator_width" value="0.065"/>
    <xacro:property name="upperarm_width" value="0.065"/>
    <xacro:property name="upperarm_length" value="0.270"/>
    <xacro:property name="upperarm_mass" value="0.300"/>
    
    <!-- Motor properties -->
    <xacro:property name="torque_constant" value="0.32"/>
    <xacro:property name="max_velocity" value="4.19"/>   <!-- rad/s -->
    <xacro:property name="max_effort" value="1.5"/>      <!-- Nm -->
    
    <!-- Materials -->
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>
    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>
    
    <!-- World link -->
    <link name="world"/>
    
    <!-- Base footprint -->
    <link name="base_footprint"/>

    <joint name="world_to_base_footprint" type="fixed">
        <parent link="world"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="base_link_fixed_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_link"/>
    
    <!-- First actuator (fixed to base) -->
    <joint name="actuator1_to_base_link" type="fixed">
        <parent link="base_link"/>
        <child link="actuator1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="actuator1">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${actuator_mass}" radius="${actuator_radius}" 
                                 length="${actuator_height}">
            <origin xyz="0 0 ${actuator_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- First joint (joint1) - Z axis rotation -->
    <joint name="joint1" type="continuous">
        <parent link="actuator1"/>
        <child link="actuator2"/>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="${max_effort}" velocity="${max_velocity}"/>
        <dynamics damping="0.1"/>
    </joint>
    
    <link name="actuator2">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual> 
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/actuator2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${actuator_mass}" x="${actuator_width}" y="${actuator_width}" z="${actuator_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Second joint (joint2) - Y axis rotation -->
    <joint name="joint2" type="revolute">
        <parent link="actuator2"/>
        <child link="upperarm_link"/>
        <origin xyz="0 ${actuator_width/2} 0.0835" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-3.14" upper="3.14" effort="${max_effort}" velocity="${max_velocity}"/>
        <dynamics damping="0.1"/>
    </joint>
        
    <link name="upperarm_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/upperarm_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/upperarm_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${upperarm_mass}" x="${upperarm_width}" y="${upperarm_width}" z="${upperarm_length}">
            <origin xyz="0 0 ${(upperarm_length - upperarm_width)/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- End effector for visualization -->
    <joint name="end_effector_joint" type="fixed">
        <parent link="upperarm_link"/>
        <child link="end_effector_link"/>
        <origin xyz="0 0 0.215" rpy="0 0 0"/>
    </joint>

    <link name="end_effector_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02" />
            </geometry>
            <material name="orange"/>
        </visual>
    </link>
    
    <!-- ros2_control hardware interface for 2 motors -->
    <ros2_control name="dual_motor_hardware" type="system">
        <hardware>
            <plugin>myactuator_hardware/MultiMotorHardwareInterface</plugin>
            <param name="ifname">$(arg can_interface)</param>
            <param name="cycle_time">5</param>
            <param name="timeout">100</param>
        </hardware>
        
        <joint name="joint1">
            <param name="actuator_id">$(arg motor1_id)</param>
            <param name="torque_constant">${torque_constant}</param>
            <command_interface name="position"/>
            <command_interface name="velocity"/>
            <command_interface name="effort"/>
            <state_interface name="position">
                <param name="initial_value">0.0</param>
            </state_interface>
            <state_interface name="velocity"/>
            <state_interface name="effort"/>
        </joint>
        
        <joint name="joint2">
            <param name="actuator_id">$(arg motor2_id)</param>
            <param name="torque_constant">${torque_constant}</param>
            <command_interface name="position"/>
            <command_interface name="velocity"/>
            <command_interface name="effort"/>
            <state_interface name="position">
                <param name="initial_value">0.0</param>
            </state_interface>
            <state_interface name="velocity"/>
            <state_interface name="effort"/>
        </joint>
    </ros2_control>

</robot>