<?xml version="1.0"?>
<robot name="manipulator_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="../inertial_macros.xacro"/>
    
    <!-- ==================== PROPERTIES ==================== -->
    <xacro:property name="meshes_file_direction" value="file://$(find robot_description)/meshes"/>

    <xacro:property name="actuator_height" value="0.061"/>
    <xacro:property name="actuator_diameter" value="0.065"/>
    <xacro:property name="actuator_radius" value="${actuator_diameter / 2}"/>
    <xacro:property name="actuator_mass" value="0.350"/>
    <xacro:property name="actuator_width" value="0.065"/>
    
    <xacro:property name="upperarm_width" value="0.065"/>
    <xacro:property name="upperarm_length" value="0.270"/>
    <xacro:property name="upperarm_mass" value="0.300"/>

    <xacro:property name="forearm_width" value="0.065"/>
    <xacro:property name="forearm_length" value="0.185"/>
    <xacro:property name="forearm_mass" value="0.176"/>

    <!-- ==================== MATERIALS ==================== -->
    <!-- Arm-specific materials (avoiding duplicates with mobile_base) -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="grey">
        <color rgba="0.2 0.2 0.2 1"/>
    </material>

    <!-- ==================== MANIPULATOR ARM ==================== -->
    <!-- Arm base link (attachment point to mobile base) -->
    <link name="arm_base_link"/>
    
    <joint name="link1_to_arm_base" type="fixed">
        <parent link="arm_base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="link1">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${actuator_mass}" radius="${actuator_radius}" 
                                 length="${actuator_height}">
            <origin xyz="0 0 ${actuator_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="link2_to_link1" type="continuous">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="link2">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual> 
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link2.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${actuator_mass}" x="${actuator_width}" y="${actuator_width}" z="${actuator_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="link3_to_link2" type="revolute">
        <parent link="link2"/>
        <child link="link3"/>
        <origin xyz="0 ${actuator_width/2} 0.0835" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="link3">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link3.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="${upperarm_mass}" x="${upperarm_width}" y="${upperarm_width}" z="${upperarm_length}">
            <origin xyz="0 0 ${(upperarm_length - upperarm_width)/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="link4_to_link3" type="revolute">
        <parent link="link3"/>
        <child link="link4"/>
        <origin xyz="0 0 0.230" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="link4">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link4.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link4.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${actuator_mass}" x="${actuator_width}" y="${actuator_width}" z="${actuator_width}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="gripper_to_link4" type="revolute">
        <parent link="link4"/>
        <child link="gripper_base"/>
        <origin xyz="0 ${-actuator_width/2} 0.225" rpy="0 -1.5707 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-3.14" upper="3.14" effort="100" velocity="100"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="gripper_base">
        <visual>
            <origin xyz="0 0 -0.01" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link5.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 -0.01" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/link5.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.160" x="0.08" y="0.05" z="0.04">
            <origin xyz="0.04 0 0" rpy="0 0 0"/> 
        </xacro:inertial_box>
    </link>

    <joint name="gripper_left_joint" type="prismatic">
        <parent link="gripper_base"/>
        <child link="gripper_left_link"/>
        <origin xyz="0.0817 0.021 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit velocity="4.8" effort="1000" lower="-0.010" upper="0.019" />
        <dynamics damping="0.1"/>
    </joint>

    <link name="gripper_left_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_left_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_left_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.020" x="0.05" y="0.01" z="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="gripper_right_joint" type="prismatic">
        <parent link="gripper_base"/>
        <child link="gripper_right_link"/>
        <origin xyz="0.0817 -0.021 0" rpy="0 0 0"/>
        <axis xyz="0 -1 0"/>
        <limit velocity="4.8" effort="1000" lower="-0.010" upper="0.019" />
        <dynamics damping="0.1"/>
        <mimic joint="gripper_left_joint" multiplier="1"/>
    </joint>

    <link name="gripper_right_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_right_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/gripper_right_palm.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.020" x="0.05" y="0.01" z="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="end_effector_joint" type="fixed">
        <parent link="gripper_base"/>
        <child link="end_effector_link"/>
        <origin xyz="0.126 0.0 0.0" rpy="0 0 0"/>
    </joint>

    <link name="end_effector_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.001" x="0.01" y="0.01" z="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="d405_to_gripper_base" type="fixed">
        <parent link="gripper_base"/>
        <child link="d405"/>
        <origin xyz="0.038 0 0.05" rpy="0 0 0"/>
    </joint>

    <link name="d405">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/d405.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="${meshes_file_direction}/d405.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.100" x="0.05" y="0.05" z="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="d405_optical_joint" type="fixed">
        <parent link="d405"/>
        <child link="d405_optical_frame"/>
        <origin xyz="0.023 0 0" rpy="0 0 0"/>
    </joint>

    <link name="d405_optical_frame"/>

</robot>